default: &default
  project_id: @@PROJECT@@
  cloud_storage:
    bucket: medicasc
    access_key_id: GOOGOSDW2K5KTH3APBAF
    secret_access_key: /7Br76VP5F4XslOsljq9WYQBiwDz25tZY4KQcFAd
  oauth2:
    client_id: @@CLIENT@@
    client_secret: @@SECRET@@

development:
  <<: *default

production:
  <<: *default
